---
title: "Plot_Physio"
author: "AndyP"
date: "4/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r load_physio}
# need to change path to location of output_physio.Rdata in active directory
load('~/Momentum/output_physio.Rdata')
load('~/Momentum/output_schedule.Rdata')
```

```{r plot_EEG, echo=FALSE}
library(ggplot2)
library(tidyverse)
library(viridis)
iS <- 2
# plot for individual subject iS out of a cached physio file
df <- output_physio$eeg$fb
name <- names(df)
df <- df[[name[iS]]]
a2f <- round(ncol(df$ch1)/4) # default times are -500 to 1500 ms for EEG
y <- rep(seq(1,nrow(df$ch1),length.out=nrow(df$ch1)),4)
name <- names(df)
dq <- rbind(df[[name[1]]],df[[name[[2]]]],df[[name[3]]],df[[name[4]]]) # concatenate channels 1-4
dq <- dq %>% mutate(session=y)
nT = nrow(df$ch1)
dq <- dq %>% mutate(channel=case_when(
  as.numeric(rownames(dq)) <= nT ~ 1,
  as.numeric(rownames(dq)) <= nT*2 & as.numeric(rownames(dq))  > nT ~ 2,
  as.numeric(rownames(dq)) <= nT*3 & as.numeric(rownames(dq)) > nT*2  ~ 3,
  as.numeric(rownames(dq)) > nT*3  ~ 4
))
dq <- dq %>% pivot_longer(cols=starts_with("V"),names_to="t", values_to="V")
dq <- dq %>% mutate(t0=as.numeric(substr(t,2,nchar(t))))
dq <- dq %>% mutate(zscore=(V-mean(V,na.rm=TRUE))/sd(V,na.rm=TRUE))
dq <- dq %>% filter(abs(zscore) <= 5)
cat('\n')
cat("<!-- This is a comment for subject", iS, "-->\n")
ggplot(dq, aes(t0,session,fill=zscore)) + geom_tile() + facet_wrap(~channel) + scale_x_continuous(breaks=c(0,a2f,max(dq$t0)),labels=c(-500,0,1500),name='time [s]') +
  geom_vline(xintercept = a2f, lty = "dashed", color = "#FF0000", size = 2) + 
  scale_fill_viridis(option = "plasma",begin=0,end=1)
cat('\n')
```

```{r plot_ECG, echo=FALSE}
library(ggplot2)
library(tidyverse)
library(viridis)
iS <- 2
# plot for individual subject iS out of a cached physio file
df <- output_physio$ecg$fb
name <- names(df)
df <- df[[name[iS]]]
a2f <- round(ncol(df)/6) # default times are -1000 to 10000 ms for ECG
y <- rep(seq(1,nrow(df),length.out=nrow(df)),1)
df <- df %>% mutate(session=y)
df <- df %>% pivot_longer(cols=starts_with("V"),names_to="t", values_to="V")
df <- df %>% mutate(t0=as.numeric(substr(t,2,nchar(t))))
df <- df %>% group_by(t0) %>% summarize(mean = mean(V, na.rm = TRUE), st_err=var(V,na.rm=TRUE)/sqrt(length(V)-sum(is.na(V))))
cat('\n')
cat("<!-- This is a comment for subject", iS, "-->\n")
ggplot(df, aes(x=t0,y=mean)) + geom_line() + geom_errorbar(aes(ymin=mean-st_err,ymax=mean+st_err),width=0.2) + scale_x_continuous(breaks=c(0,a2f,max(df$t0)),labels=c(-1000,0,100000),name='time [s]') +
  geom_vline(xintercept = a2f, lty = "dashed", color = "#FF0000", size = 2)
cat('\n')
```