---
title: Subject report
output: html_document
params:
  id: "Abbegail"
  data_root: "/Users/hallquist/Downloads/data"
---

# Individual Participant Page



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library("REDCapR")
source("report_functions.R")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(dplyr)
library("reticulate")
library("rjson")
#library("RcppArmadillo")
library("RSQLite")
library("tinsel")
library("REDCapR")
library("data.table")
if(Sys.getenv("USER")=="dp"){
  knitr::opts_knit$set(root.dir = '~/Downloads/rl_ema_monitoring', repo_path = '~/Downloads/')
  repo_path <- "~/Downloads"
  root_dir <- "~/Downloads/rl_ema_monitoring"
  source("~/Downloads/rl_ema_monitoring/EEG_Dashboard.R")
  source("~/Downloads/rl_ema_monitoring/ECG_Dashboard.R")
  source("~/Downloads/rl_ema_monitoring/dashboard/study_management/data_management_functions.R")
  source("~/Downloads/rl_ema_monitoring/dashboard/study_management/dashboard_aggregate.R")
  load("/Users/dp/Downloads/lite_proc_05_26/output_schedule.Rdata")
  load("/Users/dp/Downloads/lite_proc_05_26/output_physio.Rdata")
} else if (Sys.getenv("USER")=="abbegaillovette"){
  knitr::opts_knit$set(root.dir = '/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring', repo_path = '/Users/abbegaillovette/Documents/GitHub/')
  repo_path <<- "/Users/abbegaillovette/Documents/GitHub/"
  root_dir='/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring'
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/EEG_Dashboard.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/ECG_Dashboard.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/study_management/data_management_functions.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/study_management/dashboard_aggregate.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/study_management/RC_pull.R")
  load("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/report_generators/redcap_subj.Rdata")
  load("/Users/abbegaillovette/Desktop/lite_proc_05_26/output_physio.Rdata")
  load("/Users/abbegaillovette/Desktop/lite_proc_05_26/output_schedule.Rdata")
} else {
  source("EEG_Dashboard.R")
  source("ECG_Dashboard.R")
  source("dashboard/study_management/data_management_functions.R")
  source("dashboard/study_management/dashboard_aggregate.R")
  getwd()
  load("site/data/output_physio.Rdata") #../../../../
  load("site/data/output_schedule.Rdata")
}

rc<- redcap_pull(uri="https://www.ctsiredcap.pitt.edu/redcap/api/", token='7EB4987CE6130619646F4919D53EB0DD', activeList="221504")

#/Users/hallquist/Downloads/data/redcap.json

```

```{r load, include=FALSE}
#Not sure how subject-specific processed schedule file data and processed physio file data will be passed to this Rmd, so just loading in local RData objects and manually accessing a single subject's data for now

perf <- filter(output$subj_performance,ID==params$id) %>% filter(!is.na(date))
proc_sched <- output$proc_data[[params$id]]
info <- output$subj_info[[params$id]]
eeg <- output_physio$eeg$summary[[params$id]]
hr <- output_physio$ecg$summary[[params$id]]
checklist <- output$redcap %>% filter(ID==params$id) %>% select(`Checklist Complete?`,Date)
checklist$Date <- as.character(checklist$Date)
perf$date <- as.character(perf$date)


#get block and date columns
blk_dt <- perf %>% select(block,date) %>% rename("Date"=date)
blk_dt <- left_join(blk_dt, checklist, by="Date")
blk_dt$date <- lapply(blk_dt$Date,date_format) #reformat dates
blk_dt <- transmute(blk_dt,"Date"=date,"Block"=block, checklist=`Checklist Complete?`)
 #add whether the redcap check was completed for 
 
```



```{r video, include=FALSE}
video <- output$redcap %>% filter(ID==params$id) %>% select(`Video`,`Video Notes`,Date)
video$Date <- lapply(video$Date,date_format) %>% as.character(.)#format appropriately
video <- left_join(video,checklist,by="Date")
video$links <- "" #temporarily manually adding columns for video hyperlink

video_unchecked <- filter(video,`Checklist Complete?`=="No")

video_unchecked <- transmute(video_unchecked, "Date"= Date, "Problems" = `Video`, "Notes" = `Video Notes`, "Video" = links)
video <- transmute(video, "Date"=Date, "Problems" = `Video`, "Notes" = `Video Notes`, "Video" = links)
```



\newline
## Overview
```{r overview table, echo = FALSE, warning=FALSE}
root_dir = "../../data/Subjects"
path_info<-lapply(c("schedule","physio","video"),function(dj){
  list_id <- list.dirs(path = root_dir,recursive = F,full.names = F)
  if(dj == "video") {
    pat = ".*.mp4"
  } else {
    pat = ".db"
  }
  do.call(rbind,lapply(list_id,function(idx){
    db_files<-list.files(file.path(root_dir,idx,dj),pattern = pat,full.names = T,recursive = F,include.dirs = F)
    if(length(db_files)>0){
      dx<-data.frame(subject_id=idx,file_path=db_files,stringsAsFactors = F)
      return(dx)
    } else {
      return(NULL)
    }
  }))
})

names(path_info) <- c("schedule","physio","video")

# change this to just the regular data folder instead of site data later
rc_for_overview <- head(rc, 1)

Subject <- rc_for_overview$ID
Subject <- head(Subject, 1)
Site <- head(rc_for_overview$State,1)
Group <- head(rc_for_overview$Group,1)
Overall_Compliance <- round(output$sample_info_df$compliance, digits= 3)
rl_start <- head(rc_for_overview$`RL Start Date`,1)
RA <- head(rc_for_overview$`EMA RA`,1)
fmri_date <- head(rc_for_overview$`fMRI Date`,1)
scan_complete <- head(rc_for_overview$`Scan Complete`,1)
rl_complete <- head(rc_for_overview$rl_complete,1)
current_date <- Sys.Date()
day_sub <- difftime(current_date, rl_start, units = "days")
day_in_rl_ema <- (day_sub + 1)
days_in_rl <- ifelse(day_in_rl_ema>35,"Past 35 days/Protocol Complete",day_in_rl_ema)

#Games % Stats
Avg_Objective_Percent_Correct_No_Feedback <- output$sample_performance$abs_accurate_nofeed
Avg_Objective_Percent_Correct_No_Feedback <- round(Avg_Objective_Percent_Correct_No_Feedback, digits = 3)
Avg_Objective_Percent_Correct_Feedback <- output$sample_performance$abs_accurate_feed
Avg_Objective_Percent_Correct_Feedback <- round(Avg_Objective_Percent_Correct_Feedback, digits = 3)
Avg_Experienced_Percent_Correct_No_Feedback <- output$sample_performance$relative_accuracy_nofeed
Avg_Experienced_Percent_Correct_No_Feedback <- round(Avg_Experienced_Percent_Correct_No_Feedback, digits = 3)
Avg_Experienced_Percent_Correct_Feedback <- output$sample_performance$relative_accuracy_feed
Avg_Experienced_Percent_Correct_Feedback <- round(Avg_Experienced_Percent_Correct_Feedback, digits = 3)
#Add EEG Avg Here (named EEG_Average)
EEG_Average <- output_physio$eeg$sample_summary$avg_allCh[match(output$sample_info_df$ID, output_physio$eeg$sample_summary$ID)]
EEG_Average <- round(EEG_Average, digits = 3)
#Add HR Avg Here (named HR_Average)
hr_gen <- output_physio$ecg$sample_summary
HR_Average <- hr_gen$per_Good[match(Subject, hr_gen$ID)]*100
HR_Average <- round(HR_Average, digits = 3)
qxn <- output$sample_form_summary
#print(qxn)
ID_Overview = data.table(
  ID = Subject,
  Site = Site,
  Group = Group,
  RA = RA,
  "RL-EMA Start Date" = rl_start,
  "Current Day in Protocol" = days_in_rl,
  "fMRI date" = fmri_date,
  "fMRI completed" = scan_complete,
  "Overall Compliance" = Overall_Compliance,
  "Avg Obj Correct (no feedback)" = Avg_Objective_Percent_Correct_No_Feedback,
  "Avg Obj Correct (w/ feedback)" = Avg_Objective_Percent_Correct_Feedback,
  "Avg Rel Correct (no feedback)" = Avg_Experienced_Percent_Correct_No_Feedback,
  "Avg Rel Correct (w/ feedback)" = Avg_Experienced_Percent_Correct_Feedback,
  "EEG Average" = EEG_Average,
  "HR Average" = HR_Average,
  #"Left %" = round(output$sample_performance$side_bias, digits = 3),
  "Valence/Arousal Distance from Origin" = round(qxn$val_arr_dis_avg, digits = 3),
  "Emotion Distance from 0" = round(qxn$emo_rate_avg, digits = 3),
  "Emotion/Valence Correlation" = round(qxn$val_emo_cor, digits = 3)
)
Individual_Overview <- filter(ID_Overview, ID=="Abbegail") #change for copying for other participants
Individual_Overview<- head(Individual_Overview,1) #remove once REDCap is figured out

kbl(Individual_Overview) %>%
  kable_styling(fixed_thead = T)

```


## Individual Areas





\newline
### Sleep diary {.tabset}
#### Unchecked
```{r diary unchecked table, echo=FALSE, warning=FALSE}
#Sleep diary table
if(nrow(diary_unchecked) > 0){
  kbl(diary_unchecked) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, background=if_else(is.na(diary_unchecked[2]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(3, background=if_else(is.na(diary_unchecked[3]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(4, color=if_else(insomnia_ratio < .2, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(sleep_dist > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(sleep_dist > 50, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(sleep_dist > 50, "#D8D8D8", "black")) %>%
  column_spec(8, color=if_else(sleep_dist > 50, "#D8D8D8", "black"))
}
```

#### All blocks
```{r diary table, echo=FALSE, warning=FALSE}
if(nrow(diary) > 0){
  kbl(diary) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, background=if_else(is.na(diary[2]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(3, background=if_else(is.na(diary[3]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(4, color=if_else(insomnia_ratio < .2, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(sleep_dist > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(sleep_dist > 50, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(sleep_dist > 50, "#D8D8D8", "black")) %>%
  column_spec(8, color=if_else(sleep_dist > 50, "#D8D8D8", "black"))
}
```


\newline
### Videos {.tabset}
#### Unchecked
```{r video unchecked, echo=FALSE, warning=FALSE}
if(nrow(video_unchecked) > 0){
  kbl(video_unchecked) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, background=if_else(is.na(video_unchecked[2]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(3, background=if_else(is.na(video_unchecked[3]), "#C6EFCE", "#ffc7ce"))
}
```

#### All blocks
```{r video table, echo=FALSE, warning=FALSE}
if(nrow(video) > 0){
  kbl(video) %>%
    kable_styling(fixed_thead = T) %>%
    column_spec(1, bold = T) %>%
    column_spec(2, background=if_else(is.na(video[2]), "#C6EFCE", "#ffc7ce")) %>%
    column_spec(3, background=if_else(is.na(video[3]), "#C6EFCE", "#ffc7ce"))
}
```



