---
title: "RL EMA QA Dashboard"
output: html_document

---

```{r setup, include = FALSE}
getwd()
knitr::opts_chunk$set(comment = NA, tidy = FALSE, warning = FALSE, message = FALSE)
#source("C:/Users/tshan/rl_ema_monitoring/dashboard/study_management/data_management_functions.R")
#source("render_utils.R")
library(pacman)
p_load(DT, dplyr, htmltools, tidyr, ggplot2, plotly, widgetframe, readr)
#loads libraries and sets working directory to the root ./rl_ema_monitoring
library("data.table")
library("RSQLite")
library("plyr")
library("dplyr")
library("pixiedust")
library("ggplot2")
library("zoo")
library("tidyverse")
library("knitr")
library("reticulate")
library("lubridate")
library("rjson")
library("R.utils")
library("kableExtra")
library("widgetframe")

#getwd()
load("../site/data/output_physio.Rdata")
load("../site/data/output_schedule.Rdata")

Subject <- output$sample_info_df$ID
Site <- output$sample_info_df$State
Group <- output$sample_info_df$study_group
Overall_Compliance <- round(output$sample_info_df$compliance, digits= 3)

#Games % Stats

Avg_Objective_Percent_Correct_No_Feedback <- output$sample_performance$abs_accurate_nofeed
Avg_Objective_Percent_Correct_No_Feedback <- round(Avg_Objective_Percent_Correct_No_Feedback, digits = 3)
Avg_Objective_Percent_Correct_Feedback <- output$sample_performance$abs_accurate_feed
Avg_Objective_Percent_Correct_Feedback <- round(Avg_Objective_Percent_Correct_Feedback, digits = 3)
Avg_Experienced_Percent_Correct_No_Feedback <- output$sample_performance$relative_accuracy_nofeed
Avg_Experienced_Percent_Correct_No_Feedback <- round(Avg_Experienced_Percent_Correct_No_Feedback, digits = 3)
Avg_Experienced_Percent_Correct_Feedback <- output$sample_performance$relative_accuracy_feed
Avg_Experienced_Percent_Correct_Feedback <- round(Avg_Experienced_Percent_Correct_Feedback, digits = 3)

#Add EEG Avg Here (named EEG_Average)

EEG_Average <- output_physio$eeg$sample_summary$avg_allCh[match(output$sample_info_df$ID, output_physio$eeg$sample_summary$ID)]
EEG_Average <- round(EEG_Average, digits = 3)

#Add HR Avg Here (named HR_Average)
hr_gen <- output_physio$ecg$sample_summary
HR_Average <- hr_gen$per_Good[match(Subject, hr_gen$ID)]*100
HR_Average <- round(HR_Average, digits = 3)

qxn <- output$sample_form_summary
print(qxn)

ID_Overview = data.table(
  ID = Subject,
  Site = Site,
  Group = Group,
  "Overall Compliance" = Overall_Compliance,
  "Avg Obj Correct (no feedback)" = Avg_Objective_Percent_Correct_No_Feedback,
  "Avg Obj Correct (w/ feedback)" = Avg_Objective_Percent_Correct_Feedback,
  "Avg Rel Correct (no feedback)" = Avg_Experienced_Percent_Correct_No_Feedback,
  "Avg Rel Correct (w/ feedback)" = Avg_Experienced_Percent_Correct_Feedback,
  "EEG Average" = EEG_Average,
  "HR Average" = HR_Average,
  "Left %" = round(output$sample_performance$side_bias, digits = 3),
  "Valence/Arousal Distance from Origin" = round(qxn$val_arr_dis_avg, digits = 3),
  "Emotion Distance from 0" = round(qxn$emo_rate_avg, digits = 3),
  "Emotion/Valence Correlation" = round(qxn$val_emo_cor, digits = 3), row.names = FALSE,
)
  #TO ADD: REDCap Variables, Active/Inactive variable, link to individual page`
```

# Active Participant Overview

```{r, echo= FALSE}
#b print(ID_Overview)
#blogdown::shortcode_open("table")
#widgetframe::frameWidget(datatable(ID_Overview_Kable, class='compact', escape=FALSE, selection='none'))
kable(ID_Overview, "html") %>% kable_styling() %>% scroll_box(width = "100%") 
#blogdown::shortcode_close("table")
```


# Inactive participants

```{r, echo=FALSE}
#datatable(sdf$inactive)
```