`r paste0("## Block ", toString(i))`

```{r include=FALSE}
library(ggplot2)
library(tidyverse)
library(viridis)

# plot for individual subject iS out of a cached physio file
df <- output_physio$ecg$fb
df <- data.frame(df[[params$id]])

a2f <- round(ncol(df)/6) # default times are -1000 to 10000 ms for ECG
y <- rep(seq(1,nrow(df),length.out=nrow(df)),1)
trials <- output$proc_data[[params$id]]$raw_data$trials$trial
trials <- trials[-c(which(is.na(output$proc_data[[params$id]]$raw_data$trials$choice)))]
blocks <- output$proc_data[[params$id]]$raw_data$trials$block
blocks <- blocks[-c(which(is.na(output$proc_data[[params$id]]$raw_data$trials$choice)))]

df <- df %>% mutate(trial=trials, blocks=blocks) %>% filter(blocks==i)  

df <- df %>% pivot_longer(cols=starts_with("X"),names_to="t", values_to="X")
df <- df %>% mutate(t0=as.numeric(substr(t,2,nchar(t))))
df <- df %>% dplyr::group_by(t0) %>% dplyr::summarize(mean = mean(X, na.rm = TRUE), st_err=var(X,na.rm=TRUE)/sqrt(length(X)-sum(is.na(X))))
```

```{r echo=FALSE, include=FALSE}
# path to save the image to
#getwd()
site <- "/Users/shanebuckley/Desktop/rl_ema_monitoring/site"
# find a way to feed in the site agnostic to system later ^
#site <- "../../.."
fpath <- paste0("static/static/subjects/", params$id)
# create the directory if it doesn't exist
dir.create(path=paste0(site, "/static/static/subjects/", params$id), showWarnings = FALSE)
# save the graph as an image file
fig_name = paste0("ecg_plot_", toString(i), ".png")
# if the file doesn't exist
if (!file.exists(paste0(site, "/", fpath, "/", fig_name))) {
  # create the plot
  ecg_plot <- NULL
  try(
    ecg_plot <- ggplot(df, aes(x=t0,y=mean)) + geom_line() + geom_point() + geom_ribbon(aes(ymin = mean-st_err, ymax = mean+st_err), linetype=2, alpha=0.1) + scale_x_continuous(breaks=c(0,a2f,max(df$t0)),labels=c(-1000,0,100000),name='time [ms]') + geom_vline(xintercept = a2f, lty = "dashed", color = "#FF0000", size = 2), silent=TRUE)
  # save the image
  plotly::orca(p=ecg_plot, file=paste0("site/", fpath, "/", fig_name))
}   
```

```{r echo=FALSE}
#ggplotly(ecg_plot)
a <- paste0("/static/subjects/", params$id, "/ecg_plot_", toString(i), ".png")
a <- noquote(a)
blogdown::shortcode("graph_link", a) # 
```