
# Report {.tabset}

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../../../..') # makes root dir rl_ema_monitoring
library(kableExtra)
library(dplyr)
library("RcppArmadillo")
```

```{r source, include=FALSE, }
#knitr::opts_chunk$set(root.dir = '../../..')
source("EEG_Dashboard.R")
source("ECG_Dashboard.R")
source("dashboard/study_management/data_management_functions.R")
source("dashboard/study_management/dashboard_aggregate.R")

```

```{r load, include=FALSE}
#Not sure how subject-specific processed schedule file data and processed physio file data will be passed to this Rmd, so just loading in local RData objects and manually accessing a single subject's data for now
#load("site/data/output_schedule.Rdata") 
getwd()
load("site/data/output_physio.Rdata") #../../../../
load("site/data/output_schedule.Rdata") #../../../../

perf <- filter(output$subj_performance,ID==params$id)
proc_sched <- output$proc_data[[params$id]]
info <- output$subj_info[[params$id]]
eeg <- output_physio$eeg$summary[[params$id]]
hr <- output_physio$ecg$summary[[params$id]]
#get block and date columns
blk_dt <- perf %>% select(block,date)
blk_dt$date <- lapply(blk_dt$date,date_format) #reformat dates
blk_dt <- transmute(blk_dt,"Date"=date,"Block"=block)
 
```

```{r sleep, include=FALSE}
#Sleep diary table wrangling
diary <- proc_sched$form_dfs$`Sleep Diary`
diary$answer_time <- str_extract(diary$answer_time,"\\d{4}-\\d{2}-\\d{2}") #chop off the hour from the answer time
diary$answer_time <- lapply(diary$answer_time,date_format) #format appropriately
insomnia_ratio <- output$sample_form_summary$num_no_sleep/nrow(diary) #this will be used to determine the color of the font in the "Didn't sleep" column
diary <- transmute(diary, "Date"=answer_time, "Didn't sleep"=did_not_sleep, "Sleep latency"=sleep_latency, "Woke many times"=woke_many_times, "Woke early"=woke_early, "Overall"=overall)
diary <- arrange(diary, -row_number()) #make the most recent block come first
```

```{r mood, include=FALSE}
#Mood report table wrangling
mood <- proc_sched$form_dfs$`Mood Questionnaire`
mood$answer_time <- str_extract(mood$answer_time,"\\d{4}-\\d{2}-\\d{2}") #chop off the hour from the answer time
mood$answer_time <- lapply(mood$answer_time,date_format) #format appropriately
mood$`RA Check` <- c(1,1,1,0,1,1,1,0,1,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1) #adding RA check column, which will eventually be filled by REDCap integration
mood <- arrange(mood, -row_number()) #make the most recent block come first
mood <- transmute(mood, "Date"=answer_time, "RA Check"=`RA Check`,"Number of events"=number_of_events, "Valence"=Valence, "Arousal"=Arousal, "Anxious"=Anxious, "Elated"=Elated, "Irritable"=Irritable,"Energetic"=Energetic)
```

```{r performance, include=FALSE}
#task performance table wrangling
task <- filter(perf,!is.na(date)) #get rid of blocks not played
task$date <- lapply(task$date,date_format) #reformat dates (these dates don't come from blk_dt)
task <- arrange(task, -row_number()) #flip df so that most recent dates are first
task <- transmute(task, "Date"=date, "Block"=block, "Objective % correct (feed.)"=abs_accurate_feed, "Experienced % correct (feed.)"=relative_accuracy_feed, "Objective % correct (no feed.)"=abs_accurate_nofeed, "Experienced % correct (no feed.)"=relative_accuracy_nofeed, "RT(ms)"=mean_rt, "Left %"=IDe_bias)

#convert decimals to percentages
task$"Objective % correct (feed.)" <- task$"Objective % correct (feed.)"*100
task$"Experienced % correct (feed.)" <- task$"Experienced % correct (feed.)"*100
task$"Experienced % correct (no feed.)" <- task$"Experienced % correct (no feed.)"*100
task$"Objective % correct (no feed.)" <- task$"Objective % correct (no feed.)"*100
task$"Left %" <- task$"Left %"*100
task$"RT(ms)" <- task$"RT(ms)"*1000

task[,-c(1,2)] <- round(task[,-c(1,2)]) #round percentages to nearest whole percent

rownames(task) <- NULL
```

```{r eeg, include=FALSE}
#EEG table wrangling

eeg <- rename(eeg,"Block"=block)

eeg_dates <- left_join(eeg,blk_dt,by="Block") #add date column

eeg_avg <- mutate(eeg_dates,"avg"=(per_Ch_1 + per_Ch_2 + per_Ch_3 +per_Ch_4)/4) #create column for avg EEG signal 

eeg_row_ordered <- arrange(eeg_avg, -row_number()) #flip df so most recent blocks are first

#convert all to percentages, rounded
eeg_row_ordered$per_Ch_1 <- eeg_row_ordered$per_Ch_1*100
eeg_row_ordered$per_Ch_1 <- round(eeg_row_ordered$per_Ch_1)
eeg_row_ordered$per_Ch_2 <- eeg_row_ordered$per_Ch_2*100 
eeg_row_ordered$per_Ch_2 <- round(eeg_row_ordered$per_Ch_2)
eeg_row_ordered$per_Ch_3 <- eeg_row_ordered$per_Ch_3*100 
eeg_row_ordered$per_Ch_3 <- round(eeg_row_ordered$per_Ch_3)
eeg_row_ordered$per_Ch_4 <- eeg_row_ordered$per_Ch_4*100
eeg_row_ordered$per_Ch_4 <- round(eeg_row_ordered$per_Ch_4)
eeg_row_ordered$avg <- eeg_row_ordered$avg*100
eeg_row_ordered$avg <- round(eeg_row_ordered$avg)

eeg_col_named <- transmute(eeg_row_ordered, "Date"=Date, "Block"=Block, "Overall % good"=avg, "Ch. 1 % good"=per_Ch_1, "Ch. 2 % good"=per_Ch_2, "Ch. 3 % good"=per_Ch_3, "Ch. 4 % good"=per_Ch_4) 
```
 
```{r hr, include=FALSE}
#HR table wrangling
hr <- rename(hr,"Block"=block)

hr_dates <- left_join(hr,blk_dt,by="Block") #add date column

hr_ordered <- arrange(hr_dates, -row_number()) #most recent blocks first

#convert all to percentages, rounded
hr_ordered$per_Good <- hr_ordered$per_Good*100
hr_ordered$per_Good <- round(hr_ordered$per_Good)

hr_ordered <- transmute(hr_ordered, "Date"=Date, "Block"=Block, "Good signal %"=per_Good) 
```

```{r compliance, include=FALSE}
#compliance <-info[c("scheduled_time","delay","type", "duration")]
#compliance$scheduled_time <- as.Date(compliance$scheduled_time)
#compliance$delay <- round(as.numeric(compliance$delay), digits = 0)
#compliance$s_type[compliance$type=="trials"] <- "Behavioral Game"
#compliance$s_type[compliance$type=="questionnaires"] <- #sapply(info$spec[compliance$type=="questionnaires"],`[[`,3)
#compliance$delay <- round(compliance$delay)

#filters out NA/incomplete/upcoming data
#compliance_filtered <- compliance %>% filter(!is.na(s_type))

#compliance_filtered$is_missing <- is.na(compliance_filtered$duration)|compliance_filtered$delay>=1440
#compliance_filtered$delayednotmissing <- ifelse(compliance_filtered$is_missing, NA, compliance_filtered$delay)

#compliance_addon <- compliance_filtered[compliance_filtered$is_missing, ]

#compliance_addon$days_delayed <- floor(compliance_addon$delay/1440)

#compliance_addon$scheduled_time <- compliance_addon$scheduled_time + (compliance_addon$days_delayed)

#compliance_addon$delayednotmissing <- compliance_addon$delay - (compliance_addon$days_delayed * 1440)

#compliance_addon$days_delayed <- NULL
#compliance_addon$is_missing <- FALSE
#compliance_filtered_2 <- rbind(compliance_filtered, compliance_addon)

#line 164 (call redcap_pull via Rdata file) will need to be redone once we know how redcap integration works (with multiple subjects)

#load("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/report_generators/redcap_subj.Rdata")
#ema_checklist <- redcap_subj[c("Date", "Checklist Complete?")] 

#compliance_filtered_2$checklist <- ema_checklist$`Checklist Complete?`[match(compliance_filtered_2$scheduled_time, ema_checklist$Date)]
#print(compliance_filtered_2$checklist)

#compliance_unchecked <- compliance_filtered_2[compliance_filtered_2$checklist != "Yes"| is.na(compliance_filtered_2$checklist), ]

#pivot table
#library("pivottabler")
#compliance_pf <- PivotTable$new()
#compliance_pf$addData(compliance_filtered_2)
#compliance_pf$addColumnDataGroups("s_type", addTotal=FALSE)
#compliance_pf$addRowDataGroups("scheduled_time", addTotal=FALSE)
#compliance_pf$defineCalculation(calculationName = "delayednotmissing", summariseExpression = "ifelse(is.na(mean(as.numeric(delayednotmissing), na.rm=TRUE)), 0, mean(as.numeric(delayednotmissing), na.rm=TRUE))", caption = "avg delay")
#compliance_pf$defineCalculation(calculationName = "is_missing", summariseExpression = "length(which(is_missing))", caption = "number missing")
#compliance_pf$evaluatePivot()

#compliance_pun <- PivotTable$new()
#compliance_pun$addData(compliance_unchecked)
#compliance_pun$addColumnDataGroups("s_type", addTotal=FALSE)
#compliance_pun$addRowDataGroups("scheduled_time", addTotal=FALSE)
#compliance_pun$defineCalculation(calculationName = "delayednotmissing", summariseExpression = "ifelse(is.na(mean(as.numeric(delayednotmissing), na.rm=TRUE)), 0, mean(as.numeric(delayednotmissing), na.rm=TRUE))", caption = "avg delay")
#compliance_pun$defineCalculation(calculationName = "is_missing", summariseExpression = "length(which(is_missing))", caption = "number missing")
#compliance_pun$evaluatePivot()

# apply the green style for an average delay of between 0 and 2 hours
#cells <- compliance_pf$findCells(minValue=0, maxValue=120, includeNull=FALSE, includeNA=FALSE)
#compliance_pf$setStyling(cells=cells, declarations=list("background-color"="#C6EFCE", "color"="#006100"))

# apply the yellow style for an average delay of between 2 and 4 hours
#cells <- compliance_pf$findCells(minValue=121, maxValue=240, includeNull=FALSE, includeNA=FALSE)
#compliance_pf$setStyling(cells=cells, declarations=list("background-color"="#FFEB9C", "color"="#9C5700"))

# apply the red style for an average delay of 4 hours or greater
#cells <- compliance_pf$findCells(minValue=241, includeNull=FALSE, includeNA=FALSE)
#compliance_pf$setStyling(cells=cells, declarations=list("background-color"="#FFC7CE", "color"="#9C0006"))
```

## Task Compliance (Unchecked)
```{r compliance table, echo=FALSE}
#compliance_pun$renderPivot()
```

## Task Compliance (Full)
```{r compliance full}
#compliance_pf$renderPivot()
```

## Task performance

```{r perf table, echo=FALSE}
#Task performance table
kbl(task) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=case_when(task[,3]>80 ~ "#C6EFCE",task[,3]>70 & task[,3]<=80 ~ "#FFEB9C", task[,3]<70 ~ "#ffc7ce")) %>%
  column_spec(4, background=case_when(task[,4]>80 ~ "#C6EFCE",task[,4]>70 & task[,4]<=80 ~ "#FFEB9C", task[,4]<70 ~ "#ffc7ce")) %>%
  column_spec(5, color=ifelse(task[,5] > 55 | is.na(task[,5]), "#D8D8D8", "black")) %>%
  column_spec(6, color=ifelse(task[,6] > 55 | is.na(task[,6]), "#D8D8D8","black")) %>%
  column_spec(7, color=ifelse(task[,7] > 1400, "#E6E6E6","black")) %>%
  column_spec(8, color=ifelse(task[,8] >= 67 | task[,8] < 67, "#D8D8D8","black"))
```

## EEG

```{r two, echo=FALSE}
#EEG table
kbl(eeg_col_named) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=if_else(eeg_col_named$`Overall % good`>80, "#C6EFCE", "#ffc7ce")) %>%
  column_spec(4, color=if_else(eeg_col_named[4]>70, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(eeg_col_named[5]>70, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(eeg_col_named[6]>70, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(eeg_col_named[7]>70, "#D8D8D8", "black"))
```

## HR

```{r hr perf, echo=FALSE}
#HR table
kbl(hr_ordered) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=if_else(hr_ordered[3]>90, "#C6EFCE", "#ffc7ce"))
```

## Sleep diary

```{r diary table, warning=FALSE, echo=FALSE}
#Sleep diary table
kbl(diary) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, color=if_else(insomnia_ratio < .2, "#D8D8D8", "black")) %>%
  column_spec(3, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(4, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black"))
```

## Mood questionnaire

```{r mood table, warning=FALSE, echo=FALSE}
#Mood table
#Will need to change the figure for val_arr_dis_avg when we figure out that threshold
kbl(mood) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, background=if_else(mood[3]==1, "#C6EFCE", "#ffc7ce")) %>%
  column_spec(3, color="#D8D8D8") %>%
  column_spec(4, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(8, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(9, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black"))
```