---
title: Subject report
output: html_document
---

# Individual Participant Page {.tabset}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(dplyr)
library("RcppArmadillo")
if(Sys.getenv("USER")=="dp"){
  knitr::opts_knit$set(root.dir = '~/Downloads/rl_ema_monitoring', repo_path = '~/Downloads/')
  repo_path <- "~/Downloads"
  root_dir <- "~/Downloads/rl_ema_monitoring"
  source("~/Downloads/rl_ema_monitoring/EEG_Dashboard.R")
  source("~/Downloads/rl_ema_monitoring/ECG_Dashboard.R")
  source("~/Downloads/rl_ema_monitoring/dashboard/study_management/data_management_functions.R")
  source("~/Downloads/rl_ema_monitoring/dashboard/study_management/dashboard_aggregate.R")
  load("/Users/dp/Downloads/emp_physiooutput.Rdata") 
  load("/Users/dp/Downloads/ema_proc_05_19/output_schedule.Rdata")
} else if (Sys.getenv("USER")=="abbegaillovette"){
  knitr::opts_knit$set(root.dir = '/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring', repo_path = '/Users/abbegaillovette/Documents/GitHub/')
  repo_path <<- "/Users/abbegaillovette/Documents/GitHub/"
  root_dir='/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring'
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/EEG_Dashboard.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/ECG_Dashboard.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/study_management/data_management_functions.R")
  source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/study_management/dashboard_aggregate.R")
  load("/Users/abbegaillovette/Downloads/data_proc_05_12/data_proc_05_12/output_physio.Rdata") 
  load("/Users/abbegaillovette/Downloads/data_proc_05_12/data_proc_05_12/output.Rdata")
  load("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/report_generators/redcap_subj.Rdata")
  #load("/Users/abbegaillovette/Desktop/abb_proc_sched_5_11.Rdata")
} else {
  stop("User not recognized")
}

```

```{r load, include=FALSE}
#Not sure how subject-specific processed schedule file data and processed physio file data will be passed to this Rmd, so just loading in local RData objects and manually accessing a single subject's data for now
perf <- filter(output$subj_performance,ID=="Abbegail") %>% filter(!is.na(date))
proc_sched <- output$proc_data$'Abbegail'
info <- output$subj_info$'Abbegail'
eeg <- output_physio$eeg$summary$'Abbegail'
hr <- output_physio$ecg$summary$'Abbegail'
checklist <- output$redcap %>% filter(ID=="Abbegail") %>% select(`Checklist Complete?`,Date)
checklist$Date <- as.character(checklist$Date)
perf$date <- as.character(perf$date)

#add cumulative earnings column
sum(proc_sched$trials$outcome, na.rm=T) *.15

#get block and date columns
blk_dt <- perf %>% select(block,date) %>% rename("Date"=date)
blk_dt <- left_join(blk_dt, checklist, by="Date")
blk_dt$date <- lapply(blk_dt$Date,date_format) #reformat dates
blk_dt <- transmute(blk_dt,"Date"=Date,"Block"=block, checklist=`Checklist Complete?`)
 #add whether the redcap check was completed for 
 
```

```{r sleep, include=FALSE}
#Sleep diary table wrangling
diary <- proc_sched$form_dfs$`Sleep Diary`
diary$answer_time <- str_extract(diary$answer_time,"\\d{4}-\\d{2}-\\d{2}") #chop off the hour from the answer time
diary <- rename(diary,"Date"=answer_time)
diary <- left_join(diary,checklist, by="Date")
diary$Date <- lapply(diary$Date,date_format) #format appropriately
insomnia_ratio <- output$sample_form_summary$num_no_sleep/nrow(diary) #this will be used to determine the color of the font in the "Didn't sleep" column
#diary$did_not_sleep <- FALSE
diary <- transmute(diary, "Date"=Date, "Didn't sleep"=did_not_sleep, "Sleep latency"=sleep_latency, "Woke many times"=woke_many_times, "Woke early"=woke_early, "Overall"=overall)
diary <- arrange(diary, -row_number()) #make the most recent block come first
```

```{r mood, include=FALSE}
#Mood report table wrangling
mood <- proc_sched$form_dfs$`Mood Questionnaire`
mood$answer_time <- str_extract(mood$answer_time,"\\d{4}-\\d{2}-\\d{2}") #chop off the hour from the answer time
mood <- rename(mood,"Date"=answer_time)
mood$Date <- as.character(mood$Date)
mood <- left_join(mood,checklist, by="Date")
mood$Date <- lapply(mood$Date,date_format) #format appropriately

mood_check <- output$redcap %>% filter(ID=="Abbegail") %>% select(`Mood`,Date)
mood_check$Date <- as.character(mood_check$Date)
mood$Date <- as.character(mood$Date)

mood <- left_join(mood, mood_check, by="Date")#adding RA check column
mood <- arrange(mood, -row_number()) #make the most recent block come first

mood_unchecked <- filter(mood,`Checklist Complete?`=="No")
mood_unchecked <- transmute(mood_unchecked, "Date"=Date, "RA Check"=Mood,"Number of events"=number_of_events, "Valence"=Valence, "Arousal"=Arousal, "Anxious"=Anxious, "Elated"=Elated, "Irritable"=Irritable,"Energetic"=Energetic)
mood <- transmute(mood, "Date"=Date, "RA Check"=Mood,"Number of events"=number_of_events, "Valence"=Valence, "Arousal"=Arousal, "Anxious"=Anxious, "Elated"=Elated, "Irritable"=Irritable,"Energetic"=Energetic)
```

```{r performance, include=FALSE}
#task performance table wrangling
task <- rename(perf,"Date"=date) #get rid of blocks not played
task <- left_join(task,checklist, by="Date")
task$Date <- lapply(task$Date,date_format) #reformat dates (these dates don't come from blk_dt)
task <- arrange(task, -row_number()) #flip df so that most recent dates are first


#convert decimals to percentages
task$abs_accurate_feed <- task$abs_accurate_feed*100
task$relative_accuracy_feed <- task$relative_accuracy_feed*100
task$relative_accuracy_nofeed <- task$relative_accuracy_nofeed*100
task$abs_accurate_nofeed <- task$abs_accurate_nofeed*100
task$IDe_bias <- task$IDe_bias*100
task$mean_rt <- task$mean_rt*1000

task[,-c(1,2,9,10,11)] <- round(task[,-c(1,2,9,10,11)]) #round percentages to nearest whole percent

rownames(task) <- NULL

task_unchecked <- filter(task,`Checklist Complete?`=="No")
task_unchecked <- transmute(task_unchecked, "Date"=Date, "Block"=block, "Objective % correct (feed.)"=abs_accurate_feed, "Experienced % correct (feed.)"=relative_accuracy_feed, "Objective % correct (no feed.)"=abs_accurate_nofeed, "Experienced % correct (no feed.)"=relative_accuracy_nofeed, "RT(ms)"=mean_rt, "Left %"=IDe_bias)
task <- transmute(task, "Date"=Date, "Block"=block, "Objective % correct (feed.)"=abs_accurate_feed, "Experienced % correct (feed.)"=relative_accuracy_feed, "Objective % correct (no feed.)"=abs_accurate_nofeed, "Experienced % correct (no feed.)"=relative_accuracy_nofeed, "RT(ms)"=mean_rt, "Left %"=IDe_bias)

```

```{r eeg, include=FALSE}
#EEG table wrangling

eeg <- rename(eeg,"Block"=block)

eeg_dates <- left_join(eeg,blk_dt,by="Block") #add date and checklist column

eeg_avg <- mutate(eeg_dates,"avg"=(per_Ch_1 + per_Ch_2 + per_Ch_3 +per_Ch_4)/4) #create column for avg EEG signal 

eeg_row_ordered <- arrange(eeg_avg, -row_number()) #flip df so most recent blocks are first

#convert all to percentages, rounded
eeg_row_ordered$per_Ch_1 <- eeg_row_ordered$per_Ch_1*100
eeg_row_ordered$per_Ch_1 <- round(eeg_row_ordered$per_Ch_1)
eeg_row_ordered$per_Ch_2 <- eeg_row_ordered$per_Ch_2*100 
eeg_row_ordered$per_Ch_2 <- round(eeg_row_ordered$per_Ch_2)
eeg_row_ordered$per_Ch_3 <- eeg_row_ordered$per_Ch_3*100 
eeg_row_ordered$per_Ch_3 <- round(eeg_row_ordered$per_Ch_3)
eeg_row_ordered$per_Ch_4 <- eeg_row_ordered$per_Ch_4*100
eeg_row_ordered$per_Ch_4 <- round(eeg_row_ordered$per_Ch_4)
eeg_row_ordered$avg <- eeg_row_ordered$avg*100
eeg_row_ordered$avg <- round(eeg_row_ordered$avg)

eeg_col_named <- transmute(eeg_row_ordered, "Date"=Date, "Block"=Block, "Overall % good"=avg, "Ch. 1 % good"=per_Ch_1, "Ch. 2 % good"=per_Ch_2, "Ch. 3 % good"=per_Ch_3, "Ch. 4 % good"=per_Ch_4) 
eeg_unchecked <- filter(eeg_row_ordered, checklist=="No")
eeg_unchecked <- transmute(eeg_unchecked, "Date"=Date, "Block"=Block, "Overall % good"=avg, "Ch. 1 % good"=per_Ch_1, "Ch. 2 % good"=per_Ch_2, "Ch. 3 % good"=per_Ch_3, "Ch. 4 % good"=per_Ch_4) 
```
 
```{r hr, include=FALSE}
#HR table wrangling
hr <- rename(hr,"Block"=block)

hr_dates <- left_join(hr,blk_dt,by="Block") #add date column

hr_ordered <- arrange(hr_dates, -row_number()) #most recent blocks first

#convert all to percentages, rounded
hr_ordered$per_Good <- hr_ordered$per_Good*100
hr_ordered$per_Good <- round(hr_ordered$per_Good)

hr_unchecked <- filter(hr_ordered, checklist=="No")
hr_ordered <- transmute(hr_ordered, "Date"=Date, "Block"=Block, "Good signal %"=per_Good) 
hr_unchecked <- transmute(hr_unchecked, "Date"=Date, "Block"=Block, "Good signal %"=per_Good) 
```

```{r compliance, include=FALSE}
compliance <-info[c("scheduled_time","delay","type", "duration")]
compliance$scheduled_time <- as.Date(compliance$scheduled_time)
compliance$delay <- round(as.numeric(compliance$delay), digits = 0)
compliance$s_type[compliance$type=="trials"] <- "Behavioral Game"
compliance$s_type[compliance$type=="questionnaires"] <- sapply(info$spec[compliance$type=="questionnaires"],`[[`,3)
compliance$delay <- round(compliance$delay)

#filters out NA/incomplete/upcoming data
compliance_filtered <- compliance %>% filter(!is.na(s_type))

compliance_filtered$is_missing <- is.na(compliance_filtered$duration)|compliance_filtered$delay>=1440
compliance_filtered$delayednotmissing <- ifelse(compliance_filtered$is_missing, NA, compliance_filtered$delay)

compliance_addon <- compliance_filtered[compliance_filtered$is_missing, ]

compliance_addon$days_delayed <- floor(compliance_addon$delay/1440)

compliance_addon$scheduled_time <- compliance_addon$scheduled_time + (compliance_addon$days_delayed)

compliance_addon$delayednotmissing <- compliance_addon$delay - (compliance_addon$days_delayed * 1440)

compliance_addon$days_delayed <- NULL
compliance_addon$is_missing <- FALSE
compliance_filtered_2 <- rbind(compliance_filtered, compliance_addon)

#line 164 (call redcap_pull via Rdata file) will need to be redone once we know how redcap integration works (with multiple subjects)


ema_checklist <- output$redcap[c("Date", "Checklist Complete?")] 

compliance_filtered_2$checklist <- ema_checklist$`Checklist Complete?`[match(compliance_filtered_2$scheduled_time, ema_checklist$Date)]
print(compliance_filtered_2$checklist)

compliance_unchecked <- compliance_filtered_2[compliance_filtered_2$checklist != "Yes"| is.na(compliance_filtered_2$checklist), ]

#pivot tables


library("pivottabler")
compliance_pf <- PivotTable$new()
compliance_pf$addData(compliance_filtered_2)
compliance_pf$addColumnDataGroups("s_type", addTotal=FALSE)
compliance_pf$addRowDataGroups("scheduled_time", addTotal=FALSE)
compliance_pf$defineCalculation(calculationName = "delayednotmissing", summariseExpression = "ifelse(is.na(mean(as.numeric(delayednotmissing), na.rm=TRUE)), 0, mean(as.numeric(delayednotmissing), na.rm=TRUE))", caption = "avg delay")
compliance_pf$defineCalculation(calculationName = "is_missing", summariseExpression = "length(which(is_missing))", caption = "number missing")
compliance_pf$evaluatePivot()

compliance_pun <- PivotTable$new()
compliance_pun$addData(compliance_unchecked)
compliance_pun$addColumnDataGroups("s_type", addTotal=FALSE)
compliance_pun$addRowDataGroups("scheduled_time", addTotal=FALSE)
compliance_pun$defineCalculation(calculationName = "delayednotmissing", summariseExpression = "ifelse(is.na(mean(as.numeric(delayednotmissing), na.rm=TRUE)), 0, mean(as.numeric(delayednotmissing), na.rm=TRUE))", caption = "avg delay")
compliance_pun$defineCalculation(calculationName = "is_missing", summariseExpression = "length(which(is_missing))", caption = "number missing")
compliance_pun$evaluatePivot()

# apply the green style for an average delay of between 0 and 2 hours
cells <- compliance_pf$findCells(minValue=0, maxValue=120, includeNull=FALSE, includeNA=FALSE)
compliance_pf$setStyling(cells=cells, declarations=list("background-color"="#C6EFCE", "color"="#006100"))

# apply the yellow style for an average delay of between 2 and 4 hours
cells <- compliance_pf$findCells(minValue=121, maxValue=240, includeNull=FALSE, includeNA=FALSE)
compliance_pf$setStyling(cells=cells, declarations=list("background-color"="#FFEB9C", "color"="#9C5700"))

# apply the red style for an average delay of 4 hours or greater
cells <- compliance_pf$findCells(minValue=241, includeNull=FALSE, includeNA=FALSE)
compliance_pf$setStyling(cells=cells, declarations=list("background-color"="#FFC7CE", "color"="#9C0006"))
```

\newline
## Task Compliance (Unchecked)
```{r compliance table, echo=FALSE}
compliance_pun$renderPivot()
```

## Task Compliance (Full)
```{r compliance full, echo=FALSE}
compliance_pf$renderPivot()
```


\newline
## Task performance
#### Unchecked
```{r perf table un, echo=FALSE, warning=FALSE}
#Task performance table
kbl(task_unchecked) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=case_when(task[,3]>80 ~ "#C6EFCE",task[,3]>70 & task[,3]<=80 ~ "#FFEB9C", task[,3]<70 ~ "#ffc7ce")) %>%
  column_spec(4, background=case_when(task[,4]>80 ~ "#C6EFCE",task[,4]>70 & task[,4]<=80 ~ "#FFEB9C", task[,4]<70 ~ "#ffc7ce")) %>%
  column_spec(5, color=ifelse(task[,5] > 55 | is.na(task[,5]), "#D8D8D8", "black")) %>%
  column_spec(6, color=ifelse(task[,6] > 55 | is.na(task[,6]), "#D8D8D8","black")) %>%
  column_spec(7, color=ifelse(task[,7] > 1400, "#E6E6E6","black")) %>%
  column_spec(8, color=ifelse(task[,8] >= 67 | task[,8] < 67, "#D8D8D8","black"))
```

#### All blocks
```{r perf table, echo=FALSE, warning=FALSE}
kbl(task) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=case_when(task[,3]>80 ~ "#C6EFCE",task[,3]>70 & task[,3]<=80 ~ "#FFEB9C", task[,3]<70 ~ "#ffc7ce")) %>%
  column_spec(4, background=case_when(task[,4]>80 ~ "#C6EFCE",task[,4]>70 & task[,4]<=80 ~ "#FFEB9C", task[,4]<70 ~ "#ffc7ce")) %>%
  column_spec(5, color=ifelse(task[,5] > 55 | is.na(task[,5]), "#D8D8D8", "black")) %>%
  column_spec(6, color=ifelse(task[,6] > 55 | is.na(task[,6]), "#D8D8D8","black")) %>%
  column_spec(7, color=ifelse(task[,7] > 1400, "#E6E6E6","black")) %>%
  column_spec(8, color=ifelse(task[,8] >= 67 | task[,8] < 67, "#D8D8D8","black"))
```


\newline
## EEG
#### Unchecked
```{r two, echo=FALSE, warning=FALSE}
#EEG table
kbl(eeg_unchecked) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=if_else(eeg_col_named$`Overall % good`>80, "#C6EFCE", "#ffc7ce")) %>%
  column_spec(4, color=if_else(eeg_col_named[4]>70, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(eeg_col_named[5]>70, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(eeg_col_named[6]>70, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(eeg_col_named[7]>70, "#D8D8D8", "black"))
```

#### All blocks
```{r full, echo=FALSE, warning=FALSE}
kbl(eeg_col_named) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=if_else(eeg_col_named$`Overall % good`>80, "#C6EFCE", "#ffc7ce")) %>%
  column_spec(4, color=if_else(eeg_col_named[4]>70, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(eeg_col_named[5]>70, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(eeg_col_named[6]>70, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(eeg_col_named[7]>70, "#D8D8D8", "black"))
```

\newline
## HR
#### Unchecked
```{r unch hr, echo=FALSE, warning=FALSE}
#HR table
kbl(hr_unchecked) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=if_else(hr_ordered[3]>90, "#C6EFCE", "#ffc7ce"))
```

#### All blocks
```{r hr table, echo=FALSE, warning=FALSE}
kbl(hr_ordered) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, bold = T) %>%
  column_spec(3, background=if_else(hr_ordered[3]>90, "#C6EFCE", "#ffc7ce"))
```


\newline
## Sleep diary
```{r diary table, echo=FALSE, warning=FALSE}
#Sleep diary table
kbl(diary) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, color=if_else(insomnia_ratio < .2, "#D8D8D8", "black")) %>%
  column_spec(3, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(4, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(output$sample_form_summary$sleep_di_avg > 50, "#D8D8D8", "black"))
```

\newline
## Mood questionnaire
#### Unchecked
```{r mood unchecked, echo=FALSE, warning=FALSE}
#Mood table
#Will need to change the figure for val_arr_dis_avg when we figure out that threshold
kbl(mood_unchecked) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, background=if_else(is.na(mood[2]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(3, color="#D8D8D8") %>%
  column_spec(4, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(8, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(9, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black"))
```

#### All blocks
```{r mood table, echo=FALSE, warning=FALSE}
kbl(mood) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, background=if_else(is.na(mood[2]), "#C6EFCE", "#ffc7ce")) %>%
  column_spec(3, color="#D8D8D8") %>%
  column_spec(4, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(5, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(6, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(7, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(8, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black")) %>%
  column_spec(9, color=if_else(output$sample_form_summary$val_arr_dis_avg > 50, "#D8D8D8", "black"))
```
```




