
function mergeParticipantFiles(participantsDir, eventName, timeBinIdx, binningMode, freqIdx, sessionIdx, sectionsToMerge)
   
    if nargin < 5; freqIdx = NaN; end
    if nargin< 6; sessionIdx = 0; end
    if nargin<7; sectionsToMerge = {''}; end
    fprintf("Processing started %s \n",datetime());
    tic;
    % create merger
    merger = MomentumParticipantMerger(participantsDir);

    merger.merge( ...
        eventName      = eventName, ...
        sectionsToMerge= sectionsToMerge, ...
        freqLabel      = freqIdx, ...
        binningMode    = binningMode, ...
        timeBinIdx     = timeBinIdx, ...
        sessionBinIdx  = sessionIdx, ...
        extension      = ".parquet" ...
    );
    fprintf("Processing finished %s \n",datetime());
    toc;
end
