---
title: "RL EMA QA Dashboard"
output: html_document
---

```{r setup, include = FALSE, cache=TRUE, cache.lazy=FALSE}
knitr::opts_knit$set(comment = NA, tidy = FALSE, warning = FALSE, message = FALSE, root.dir = '../..')
#knitr::opts_knit$set() # makes root dir
getwd()
#source("C:/Users/tshan/rl_ema_monitoring/dashboard/study_management/data_management_functions.R")
#source("render_utils.R")
library(pacman)
p_load(DT, dplyr, htmltools, tidyr, ggplot2, plotly, widgetframe, readr)
#loads libraries and sets working directory to the root ./rl_ema_monitoring
library("data.table")
library("RSQLite")
library("plyr")
library("dplyr")
library("pixiedust")
library("ggplot2")
library("zoo")
library("tidyverse")
library("knitr")
library("reticulate")
library("lubridate")
library("rjson")
library("R.utils")
library("kableExtra")
```

```{r load, include = FALSE, cache=TRUE, cache.lazy=FALSE}
#setwd("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/")
# starting in rl_ema_monitoring/site/
#root_dir = dirname(dirname(getwd())) #"/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/"
#source(file.path(root_dir,"dashboard/study_management/data_management_functions.R"))
#root_dir = dirname(dirname(getwd()))
#source(file.path(root_dir,"dashboard/study_management/dashboard_aggregate.R"))
#root_dir = dirname(dirname(getwd()))
#source(file.path(root_dir,"EEG_Dashboard.R"))
#root_dir = dirname(dirname(getwd()))
#source(file.path(root_dir,"ECG_Dashboard.R"))
getwd()
source("../../dashboard/study_management/data_management_functions.R")
#root_dir = dirname(dirname(getwd()))
source("../../dashboard/study_management/dashboard_aggregate.R")
#root_dir = dirname(dirname(getwd()))
source("../../EEG_Dashboard.R")
#root_dir = dirname(dirname(getwd()))
source("../../ECG_Dashboard.R")
#root_dir = dirname(dirname(getwd()))
#getwd()
root_dir = "../../data/Subjects"
path_info<-lapply(c("schedule","physio","video"),function(dj){
  list_id <- list.dirs(path = root_dir,recursive = F,full.names = F)
  if(dj == "video") {
    pat = ".*.mp4"
  } else {
    pat = ".db"
  }
  do.call(rbind,lapply(list_id,function(idx){
    db_files<-list.files(file.path(root_dir,idx,dj),pattern = pat,full.names = T,recursive = F,include.dirs = F)
    if(length(db_files)>0){
      dx<-data.frame(subject_id=idx,file_path=db_files,stringsAsFactors = F)
      return(dx)
    } else {
      return(NULL)
    }
  }))
})

names(path_info) <- c("schedule","physio","video")

# change this to just the regular data folder instead of site data later
load("../data/output_physio.Rdata")
load("../data/output_schedule.Rdata")

Subject <- output$sample_info_df$ID
Site <- output$sample_info_df$State
Group <- output$sample_info_df$study_group
Overall_Compliance <- round(output$sample_info_df$compliance, digits= 3)

#Games % Stats
Avg_Objective_Percent_Correct_No_Feedback <- output$sample_performance$abs_accurate_nofeed
Avg_Objective_Percent_Correct_No_Feedback <- round(Avg_Objective_Percent_Correct_No_Feedback, digits = 3)
Avg_Objective_Percent_Correct_Feedback <- output$sample_performance$abs_accurate_feed
Avg_Objective_Percent_Correct_Feedback <- round(Avg_Objective_Percent_Correct_Feedback, digits = 3)
Avg_Experienced_Percent_Correct_No_Feedback <- output$sample_performance$relative_accuracy_nofeed
Avg_Experienced_Percent_Correct_No_Feedback <- round(Avg_Experienced_Percent_Correct_No_Feedback, digits = 3)
Avg_Experienced_Percent_Correct_Feedback <- output$sample_performance$relative_accuracy_feed
Avg_Experienced_Percent_Correct_Feedback <- round(Avg_Experienced_Percent_Correct_Feedback, digits = 3)
#Add EEG Avg Here (named EEG_Average)
EEG_Average <- output_physio$eeg$sample_summary$avg_allCh[match(output$sample_info_df$ID, output_physio$eeg$sample_summary$ID)]
EEG_Average <- round(EEG_Average, digits = 3)
#Add HR Avg Here (named HR_Average)
hr_gen <- output_physio$ecg$sample_summary
HR_Average <- hr_gen$per_Good[match(Subject, hr_gen$ID)]*100
HR_Average <- round(HR_Average, digits = 3)
qxn <- output$sample_form_summary
print(qxn)
ID_Overview = data.table(
  ID = Subject,
  Site = Site,
  Group = Group,
  "Overall Compliance" = Overall_Compliance,
  "Avg Obj Correct (no feedback)" = Avg_Objective_Percent_Correct_No_Feedback,
  "Avg Obj Correct (w/ feedback)" = Avg_Objective_Percent_Correct_Feedback,
  "Avg Rel Correct (no feedback)" = Avg_Experienced_Percent_Correct_No_Feedback,
  "Avg Rel Correct (w/ feedback)" = Avg_Experienced_Percent_Correct_Feedback,
  "EEG Average" = EEG_Average,
  "HR Average" = HR_Average,
  "Left %" = round(output$sample_performance$side_bias, digits = 3),
  "Valence/Arousal Distance from Origin" = round(qxn$val_arr_dis_avg, digits = 3),
  "Emotion Distance from 0" = round(qxn$emo_rate_avg, digits = 3),
  "Emotion/Valence Correlation" = round(qxn$val_emo_cor, digits = 3)
)
#TO ADD: REDCap Variables, Active/Inactive variable, link to individual page`
```

```{r active_split, echo=FALSE, warning=FALSE, dependson="load"}
pacman::p_load(reticulate)
ids <- list("abbegail") #tolower(ID_Overview$ID)
# use paste0 to compose markdown-formatted hyperlinks
ID_Overview$ID <- paste0("<a target='_parent' href='/",ids, "/'>", ID_Overview$ID, "</a>") # subjects/
# create a new folder and rmd template if for each subject that hasn't been initialized
for(id in ids) {
  # if the path does not exist
  #if(dir.exists(paste0('subjects/', id)) == FALSE) {
  #  # then create the directory
  #  dir.create(paste0('subjects/', id))
  #}
  # if the path does not exist
  #if(dir.exists(paste0('subjects/', id, '/graphs')) == FALSE) {
  #  # then create the directory
  #  dir.create(paste0('subjects/', id, '/graphs'))
  #}
  curr_path <- paste0('subjects/', id)
  # if the md and the Rmd for the subject does not exist
  if(file.exists(paste0(curr_path, '/_index.Rmd')) == FALSE) {
    tryCatch({
      # then create a subject Rmd from the template
      blogdown::hugo_cmd(paste0("new subjects/", id, " -s .."))
    })
    tryCatch({
      # rename the .md file to a .Rmd (this allows Go to be used properly in archetypes)
    file.rename(paste0(curr_path, "/_index.md"), paste0(curr_path, "/_index.Rmd"))
    })
  }
  # attempt to render the subject's graph pages
  if(file.exists(paste0(curr_path, '/plot_ecg.Rmd')) == FALSE) {
    tryCatch({
      # rename the .md file to a .Rmd (this allows Go to be used properly in archetypes)
    file.rename(paste0(curr_path, '/plot_ecg.md'), paste0(curr_path, '/plot_ecg.Rmd'))
    })
  }
  # attempt to render the subject's graph pages
  if(file.exists(paste0(curr_path, '/plot_eeg.Rmd')) == FALSE) {
    tryCatch({
      # rename the .md file to a .Rmd (this allows Go to be used properly in archetypes)
    file.rename(paste0(curr_path, '/plot_eeg.md'), paste0(curr_path, '/plot_eeg.Rmd'))
    })
  }
}
#reticulate::use_condaenv('/Users/shanebuckley/Library/r-miniconda/envs/r-reticulate')
# get the active subjects
active_list <- getActiveList(root_dir="rl_ema_monitoring")
# make DT with only active subjects
Active_Overview <- subset(ID_Overview, !(ID %in% active_list))
# make DT with only inactive subjects
Inactive_Overview <- subset(ID_Overview, (ID %in% active_list))
```

# Active Participant Overview
```{css, echo=FALSE}
pre, code {white-space:pre !important; overflow-x:auto}
```

```{r, echo=FALSE}
#b print(ID_Overview)
library("kableExtra")
library(pacman)
p_load(DT, dplyr, htmltools, tidyr, ggplot2, plotly, widgetframe, readr)
widgetframe::frameWidget(datatable(Active_Overview, class='compact', escape=1, selection='none', extensions = "Scroller", options = list(scrollX = TRUE, scroller = TRUE))) # Active 

#kable(Active_Overview, "html") %>% kable_styling() %>% scroll_box(width = "100%") 
```

# Inactive Participant Overview

```{r, echo=FALSE}
library("kableExtra")
library(pacman)
p_load(DT, dplyr, htmltools, tidyr, ggplot2, plotly, widgetframe, readr)
#blogdown::shortcode_open("table")
widgetframe::frameWidget(datatable(Inactive_Overview, class='compact', escape=1, selection='none', extensions = "Scroller", options = list(scrollX = TRUE, scroller = TRUE)))

#kable(Inactive_Overview, "html") %>% kable_styling() %>% scroll_box(width = "100%") 
```
