---
title: "Flagged"
output: html_document
---

```{r, include = FALSE}
library(kableExtra)
library(tidyverse)

source("/Users/abbegaillovette/Documents/GitHub/rl_ema_monitoring/dashboard/study_management/RC_pull.R")
rc <- redcap_pull(uri="https://www.ctsiredcap.pitt.edu/redcap/api/", token='ED9A370F44BD175F8C9AD9D68DF5710D', activeList=c("30497", "Abbegail", "Amy", "Shane", "123"))
flagged <- rc %>% filter(`Flagged?`=="Yes") %>% select(ID, Group, Day, Date, `Overall Issues`, Compliance, `Task Performance`, EEGHR, Sleep, Mood, Video)

#add recent filter with new participants 
# current_date <- Sys.Date()
# time_since_checked <- difftime(current_date, rc$`Date`, units = "days")
# flagged <- filter(flagged, time_since_checked < 8)
```

```{r flagged, echo=FALSE}
kbl(flagged) %>%
  kable_styling(fixed_thead = T) %>%
  column_spec(1, bold=TRUE) %>%
  column_spec(5, background="#c3c1c1", color="black", border_left=TRUE, bold=TRUE, width_min="200px") %>%
  column_spec(6, background=ifelse(is.na(flagged$`Compliance`), "#c3c1c1", "#f04c57"), 
              color="white", border_left=TRUE, width_min="150px") %>%
  column_spec(7, background=ifelse(is.na(flagged$`Task Performance`), "#c3c1c1", "#f04c57"), 
              color="white", border_left=TRUE, width_min="150px") %>%
  column_spec(8, background=ifelse(is.na(flagged$`EEGHR`), "#c3c1c1", "#f04c57"), 
              color="white", border_left=TRUE, width_min="150px") %>%
  column_spec(9, background=ifelse(is.na(flagged$`Sleep`), "#c3c1c1", "#f04c57"), 
              color="white", border_left=TRUE, width_min="150px") %>%
  column_spec(10, background=ifelse(is.na(flagged$`Mood`), "#c3c1c1", "#f04c57"), 
              color="white", border_left=TRUE, width_min="150px") %>%
  column_spec(11, background=ifelse(is.na(flagged$`Video`), "#c3c1c1", "#f04c57"), 
              color="white", border_left=TRUE, width_min="150px") 
```

